### ISSUE TITLE
请问您怎么在本地运行demo

### ISSUE THREAD

**Issue by zhaozhao626** [SamuelGong/FLASHE#3]
不好意思，打扰到您了，请问本地怎么运行demo？
我看了readme，在[simulation](https://github.com/SamuelGong/FLASHE/tree/master/simulation)中，什么也没有，是没有上传文件吗

**Comment by SamuelGong** [comment]
> 不好意思，打扰到您了，请问本地怎么运行demo？ 我看了readme，在[simulation](https://github.com/SamuelGong/FLASHE/tree/master/simulation)中，什么也没有，是没有上传文件吗

Hi,

Thanks for reaching out. FLASHE’s complete code is being reframed for ease of use, though, for reproducing Table 2 with local PC simulation, you can try the preliminary code via 

https://github.com/SamuelGong/FLASHE/blob/e69778c5c7ec8c5741dd9076fd33e54a0d5d5ed6/encrypt_test/final_big_table.ipynb

It should be runnable after all necessary dependencies get installed. Please comment below if you encounter any further issue:)

**Comment by jingluo168** [comment]
> 不好意思，打扰到您了，请问本地怎么运行demo？ 我看了readme，在[模拟](https://github.com/SamuelGong/FLASHE/tree/master/simulation)中，什么也没有，是没有上传文件吗

你好，我想请问一下，你运行final_big_table.ipynb 测试时，遇到这样的问题吗

![Image](https://github.com/user-attachments/assets/e7a46775-2e69-46c3-9c6d-35309741776a)

![Image](https://github.com/user-attachments/assets/e6232c0c-89a5-4e97-bf95-ea65299451bc)
发生异常: TypeError
contextGen() takes at least 2 positional arguments (0 given)
  File "F:\FLASHE-master\encrypt_test\federatedml\secureprotol\jzf_bfv.py", line 70, in generate_key
    self.he.contextGen(p=self.p, m=self.m,sec=self.sec, flagBatching=self.flagBatching)
  File "F:\FLASHE-master\encrypt_test\P_B-C", line 144, in <module>
    bfv.generate_key()
TypeError: contextGen() takes at least 2 positional arguments (0 given)

**Comment by zhaozhao626** [comment]
import tenseal as ts 你可以试试这个库 构建BFV 具体怎么使用我觉得你可以问问ChatGPT

**Comment by jingluo168** [comment]
好的，谢谢



---原始邮件---
发件人: "Dylan ***@***.***&gt;
发送时间: 2025年2月23日(周日) 下午4:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SamuelGong/FLASHE] 请问您怎么在本地运行demo (Issue #3)


   
import tenseal as ts 你可以试试这个库 构建BFV 具体怎么使用我觉得你可以问问ChatGPT

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  zhaozhao626 left a comment (SamuelGong/FLASHE#3)
 
import tenseal as ts 你可以试试这个库 构建BFV 具体怎么使用我觉得你可以问问ChatGPT
