### ISSUE TITLE
issue about "jzf_flashe.py"

### ISSUE THREAD

**Issue by zhaozhao626** [SamuelGong/FLASHE#7]
您好，作者！

## issue 1
请问下面这个function的目的是什么？
https://github.com/SamuelGong/FLASHE/blob/d18303bbb088bf416c9d81aa1c8a13857867758a/federatedml/secureprotol/jzf_flashe.py#L12
## issue 2
在下面这个文件中的line 24-26，meaning of the variables 
https://github.com/SamuelGong/FLASHE/blob/d18303bbb088bf416c9d81aa1c8a13857867758a/federatedml/secureprotol/jzf_flashe.py#L24

## issue 3
请问如果要将您的这个方案应用至deep Learning中，在每个epoch完成后，需要重新设置这两个吗？
```
flashe.set_iter_index(epoch)
flashe.idx = 0
```
劳烦，作者回答上述的3个issue。
如果我有表达不清楚的地方，请您指出，谢谢您！

**Comment by zhaozhao626** [comment]
作者，您好！
这是我对issue的理解，请问是否正确？
功能是将一个列表分成指定大小的若干个块，并返回每个块的起始索引和结束索引。函数的参数说明如下：

l：列表，即要分块的列表。
n：整数，即要将列表分成的块的数量。
函数的具体实现方法如下：

首先，使用 Python 内置函数 divmod() 求出每个块的大小和数量的余数。divmod(a, b) 函数返回元组 (a // b, a % b)，即 a 除以 b 的商和余数。

然后，使用 Python 的 for 循环语句遍历每个块，计算每个块的起始索引和结束索引。具体计算方法如下：

si 表示当前块的起始索引。对于前 r 个块，每个块的大小为 (d+1)，所以起始索引为 (d+1)*i。对于后面的 (n-r) 个块，每个块的大小为 d，所以起始索引为 (d+1)*r + d*(i-r)。
d+1 表示前 r 个块的大小，d 表示后面的 (n-r) 个块的大小。因为有余数，所以前 r 个块的大小比后面的 (n-r) 个块的大小多 1。
最后，使用 Python 的 yield 语句将每个块的起始索引和结束索引返回给调用方，而不是一次性返回所有块，以节省内存。

**Comment by SamuelGong** [comment]
Thank you for reaching out! Let me reply to your question one by one.

## Issue 1

> 作者，您好！ 这是我对issue的理解，请问是否正确？ 功能是将一个列表分成指定大小的若干个块，并返回每个块的起始索引和结束索引。函数的参数说明如下：
> 
> l：列表，即要分块的列表。 n：整数，即要将列表分成的块的数量。 函数的具体实现方法如下：
> 
> 首先，使用 Python 内置函数 divmod() 求出每个块的大小和数量的余数。divmod(a, b) 函数返回元组 (a // b, a % b)，即 a 除以 b 的商和余数。
> 
> 然后，使用 Python 的 for 循环语句遍历每个块，计算每个块的起始索引和结束索引。具体计算方法如下：
> 
> si 表示当前块的起始索引。对于前 r 个块，每个块的大小为 (d+1)，所以起始索引为 (d+1)*i。对于后面的 (n-r) 个块，每个块的大小为 d，所以起始索引为 (d+1)_r + d_(i-r)。 d+1 表示前 r 个块的大小，d 表示后面的 (n-r) 个块的大小。因为有余数，所以前 r 个块的大小比后面的 (n-r) 个块的大小多 1。 最后，使用 Python 的 yield 语句将每个块的起始索引和结束索引返回给调用方，而不是一次性返回所有块，以节省内存。

Your understandings are precisely what `chunks_idx` is for and how it works :D The only thing I want to add is why we need this utility function--it's for multicore processing purposes. `chunks_idx` actually helps us evenly distribute specific data (e.g., an array of integers like [here](https://github.com/SamuelGong/FLASHE/blob/d18303bbb088bf416c9d81aa1c8a13857867758a/federatedml/secureprotol/jzf_flashe.py#L321)) into multiple chunks, so that we can fully utilize the CPU cores via feeding each data chunk to a CPU core for parallel processing.

## Issue 2

To understand the meaning of those variables, first, take a look at this line of code

https://github.com/SamuelGong/FLASHE/blob/d18303bbb088bf416c9d81aa1c8a13857867758a/federatedml/secureprotol/jzf_flashe.py#L36

Here is where we prepare masks (pseudorandom numbers) in advance for efficient encryption.

By calling `local_prp.get_permutation()` we obtain a secure pseudorandom number `add_term_bytes`, whose length is 16 bytes, or 128 bits. In other words, we obtain 128 random bits. These bits are sufficient for us to encrypt one 128-bit integer, or two 64-bit integers, or four 32-bit integers... By 'merging', we can fully utilize these 128 random bits to encrypt as many integers as possible in one go, and this is why the variables you referred to have `merge` in their names.

Next, I could explain the meaning of them through a concrete example: suppose our plaintext is 100 elements, each of which is a 20-bit integer. First, because 6 * 20 < 128 < 7 * 20, by calling `local_prp.get_permutation()` we can generate at most `128 // 20 = 6` (definition of `merge_size`) independent 20-bit masks at a time. Next, because 16 * 6 < 100 < 17 * 6, we need to call `local_prp.get_permutation()` for at least `(100 - 1) // 6 + 1 = 17` (definition of `merge_num`) times to generate all the 100 masks for encryption.

## Issue 3

For each training round `epoch`, yes, you need to execute `flashe.set_iter_index(epoch)` correspondingly. Otherwise, the system will always use the same masks to encrypt across all epochs.

On the other hand, `flashe.idx` means the client index and it should only be set once, as a client's ID does not vary as the training proceeds. In the Jupyter notebook, we are in a single-node simulation, so we have only one client, and by convention, we index the client as `0`, and that is why we do `flashe.idx = 0`.

Please let me know if you have further questions.

**Comment by zhaozhao626** [comment]
感谢您的回答，您的回答条理清晰，易懂，并且举例很清楚，对我理解code很有帮助，非常感谢！

**Comment by SamuelGong** [comment]
You are welcome!
