### ISSUE TITLE
about generate data 

### ISSUE THREAD

**Issue by zhaozhao626** [SamuelGong/FLASHE#8]
您好，在我运行您的代码是，当生成数据是负数的时候，最后的结果是错的
e.g. 我只是简单的将生成的random数，变成了负数
`’plaintext = np.random.random(plaintext_length) - 2`
最后的结果就不正确了。
![image](https://user-images.githubusercontent.com/82107239/226173681-c074c4c5-6b25-4a2a-93bd-8fc033eb439c.png)

**Comment by SamuelGong** [comment]
Hi there,

Thank you for reaching out. It seems that the automatically calculated clipping bound in `jzf_aciq.py` is too small.

This is not a bug, as ACIQ/dACIQ (which determines the clipping bound when quantization) has assumed that the average value in the plaintext data is zero (we do not lose generality since we can always subtract and add this mean). However, when you subtract 2 from X where X is uniformly sampled from [0, 1], the mean of X is -2.5.

Therefore, this has nothing to do with FLASHE (or any other implemented encryption scheme). Instead, this is related to our quantization scheme (which converts floating-point numbers into integers in the context of FL). If one wants to use our quantization scheme, she has to be careful to ensure that the plaintext has a mean of 0, otherwise, she cannot obtain the expected sum. On the other hand, one can also opt to use another quantization scheme, so long as it fits the encryption scheme she uses and does not violate her threat model and other requirements.

**Comment by zhaozhao626** [comment]
非常感谢您的回答，正如您所说一样，是我的量化方案选择不恰当。
当我在量化梯度值为负数时，最后得到的聚合结果是错误的，反之量化0或正数时，就是正确的。
这个量化方案的问题困扰了我很久，很希望你能给予我一些建议。
诚恳期望收到您的建议。
您的读者

**Comment by SamuelGong** [comment]
In fact, **to make the mean zero** without violating the privacy requirement before encryption--this is exactly the solution I have provided in the last comment.

In your example, that is,

```Python
plaintext = np.random.random(plaintext_length) - 2
plaintext += 1.5  # Because  plaintext is originally uniformly distributed in [0 - 2, 1 - 2] = [-2, -1], and thus the mean is -1.5
# 
# ... (the whole aggregation process)
# 
final_sum -= 1.5 * 10 
```

So long as the number of operands for addition (e.g., number of participating clients in FL) and the enforced mean are both public knowledges, you can regard this transformation as a legitimate preprocessing that can be done before encryption.

**Comment by zhaozhao626** [comment]
谢谢您，在看到您的建议之后，醍醐灌顶，衷心的感谢您的指导！
